In [70]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
tr_df =  np.loadtxt("0000000000002419_training_ccpp_x_y_train.csv",delimiter=",")
#tr_df.shape[1]
scaler = preprocessing.StandardScaler()
scaler.fit(tr_df)

scaler.transform(tr_df)

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00,
         7.58624590e-01,  1.62423942e+00],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01,
        -4.46921842e-01, -4.37233891e-01],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01,
         3.75010552e-01, -1.09219167e-01],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01,
        -5.83682640e-01, -9.79450400e-01],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01,
        -6.59584883e-01,  3.23269996e-01],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01,
        -1.73110573e+00, -5.84315226e-01]])

In [71]:
def step_grad(points, learn_rate, M):
    N = points.shape[0]
    num_col = points.shape[1]
    
    new_M = np.zeros(num_col)
    
    for i in range(N):
        x = points[i, 0:num_col-1]
        x = np.append(x, 1)
        y = points[i, num_col-1]
        for j in range(num_col):
            new_M[j] += (-2/N) * (y - (M * x).sum()) * x[j]
        M = M - (learn_rate * new_M)
        
    #print (M.shape)
    return M

In [72]:
def gd(points, learn_rate, num_iter):
    num_col = points.shape[1]
    M = np.zeros(num_col)
    
    for i in range(num_iter):
        M = step_grad(points, learn_rate, M)
#         if i % 100== 0:
#             print(i, "Cost= ", cost(points, M))
    #print(i, "Cost= ", cost(points, M))
    return M

In [73]:
def cost(points, M):
    total_cost = 0
    
    N = points.shape[0]
    num_col = points.shape[1]
    
    for i in range(N):
        x = points[i,0:num_col-1]
        x = np.append(x, 1)
        y = points[i,num_col-1]
        total_cost += (y - (M * x).sum()) ** 2
        
    total_cost = (1/N) * total_cost
    return total_cost

In [78]:
def run():
    #= pd.read_csv("/Users/shagunsaboo/Downloads/trainb.csv")
    learning_rate = 0.00001
    num_iterations = 1000
    m = gd(tr_df, learning_rate, num_iterations)
    print (m.size)
    print(m, c)
    return m[0:4], m[4]

In [79]:
m,c=run()
print(m,c)

5
[-3.45628359 -3.89917151  0.42066753  4.07245427  1.36272214] 22.013737506684336
[-3.45628359 -3.89917151  0.42066753  4.07245427] 1.3627221431676957


In [80]:
test_data =np.loadtxt("0000000000002419_test_ccpp_x_test.csv", delimiter=",")

scaler.fit(test_data)

scaler.transform(test_data)

array([[-1.05179958, -0.9803295 ,  0.73940279,  1.20354042],
       [-1.03554677, -1.28089884, -0.09850361,  0.5680886 ],
       [ 0.97438468,  1.64050792, -1.29819445,  0.38358038],
       ...,
       [ 0.62359476,  0.94554072, -0.70944148,  1.27238677],
       [ 0.51117945, -0.91910241,  0.1216388 , -0.55754924],
       [ 0.27686804,  0.47003684,  0.97490397,  0.80216619]])

In [81]:
from sklearn.ensemble import GradientBoostingRegressor

In [82]:
x = tr_df[:, :-1]
y = tr_df[:, -1]

In [83]:
reg=GradientBoostingRegressor()
reg.fit(x,y)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [84]:
y_predict=reg.predict(test_data)

In [85]:
y_predict

array([470.56174391, 472.66297342, 435.27765416, ..., 438.71921598,
       452.8264231 , 445.09956345])

In [86]:
def predict(x, m, c):
    N = x.shape[0]
    y = np.zeros(N)
    
    for i in range(N):
        X = x[i,:]
        y[i] = (m * X).sum() + c
        
    return y

In [87]:
x_test = test_data

In [88]:
y_pred = predict(x_test, m, c)

In [89]:
y_pred

array([594.38619238, 569.0560762 , 360.63779622, ..., 457.69501728,
       445.80212114, 466.19727484])

In [90]:
y_predict.mean()

454.21968098846713

In [91]:
np.savetxt("predictedboston3.csv", y_predict, delimiter=',')